# https://docs.github.com/en/actions

# https://github.com/ahmadnassri/action-dependabot-auto-merge

name: dependabot-auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.4
        if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
        with:
          github-token: ${{ secrets.AUTO_MERGE }}
